---
# handlers file for clickhouse-role
- name: Restart clickhouse service
  become: true
  ansible.builtin.service:
    name: clickhouse-server
    state: restarted
- name: start clickhouse-server(sysemctl)
  become: true
  ansible.builtin.command: "systemctl start clickhouse-server.service"
  ignore_errors: yes